webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    script_attributes:
        defer: true
    builds:
        main: '%kernel.project_dir%/public/build/main'
        admin: '%kernel.project_dir%/public/build/admin'
